[features]
seeds = false
skip-lint = false

[programs.localnet]
coinflip = "7ttfENVhNwb21KjZiLHgXLsX2sC1rKoJgnTVL4wb54t1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/root/fury/ubuntu-deploy.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
